# Generated by Django 4.0.4 on 2022-06-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut'),
        ),
    ]
